---
spring:
  datasource:
    druid:
      min-idle: 10
      web-stat-filter:
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*"
      stat-view-servlet:
        login-password: druid
        login-username: druid
      max-active: 20
      initial-size: 5
    url: jdbc:mysql://localhost/mall?useUnicode=true&characterEncoding=utf-8
    username: reader
    password: 123456